// Generated by Apple Swift version 5.3.2 (swiftlang-1200.0.45 clang-1200.0.32.28)
#ifndef VIDEOEDITORIOS_SWIFT_H
#define VIDEOEDITORIOS_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <Foundation/Foundation.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(ns_consumed)
# define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
#else
# define SWIFT_RELEASES_ARGUMENT
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if !defined(IBSegueAction)
# define IBSegueAction
#endif
#if __has_feature(modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import AVFoundation;
@import AssetsPickerViewController;
@import CoreGraphics;
@import Foundation;
@import ObjectiveC;
@import UIKit;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="VideoEditoriOS",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif



@class NSCoder;

IB_DESIGNABLE
SWIFT_CLASS("_TtC14VideoEditoriOS15AnchorPointView")
@interface AnchorPointView : UIView
@property (nonatomic) IBInspectable BOOL showAnchorPoint;
@property (nonatomic) IBInspectable CGPoint anchorPoint;
- (void)drawRect:(CGRect)rect;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

@class UIWindow;
@class UIApplication;

SWIFT_CLASS("_TtC14VideoEditoriOS11AppDelegate") SWIFT_AVAILABILITY(ios,introduced=13.0)
@interface AppDelegate : UIResponder <UIApplicationDelegate>
@property (nonatomic, strong) UIWindow * _Nullable window;
- (BOOL)application:(UIApplication * _Nonnull)application didFinishLaunchingWithOptions:(NSDictionary<UIApplicationLaunchOptionsKey, id> * _Nullable)launchOptions SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class UIColor;

IB_DESIGNABLE
SWIFT_CLASS("_TtC14VideoEditoriOS8CardView")
@interface CardView : UIView
@property (nonatomic) IBInspectable CGFloat cornerRadius;
@property (nonatomic) IBInspectable NSInteger shadowOffsetWidth;
@property (nonatomic) IBInspectable NSInteger shadowOffsetHeight;
@property (nonatomic, strong) IBInspectable UIColor * _Nullable shadowColor;
@property (nonatomic) IBInspectable float shadowOpacity;
@property (nonatomic) IBInspectable BOOL cardView;
- (void)layoutSubviews;
@property (nonatomic, strong) IBInspectable UIColor * _Nonnull firstColor;
@property (nonatomic, strong) IBInspectable UIColor * _Nonnull secondColor;
@property (nonatomic, strong) IBInspectable UIColor * _Nonnull therdColor;
@property (nonatomic) IBInspectable BOOL horizontalGradient;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) Class _Nonnull layerClass;)
+ (Class _Nonnull)layerClass SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

@class UIImageView;
@class UILabel;

SWIFT_CLASS("_TtC14VideoEditoriOS15GalleryItemCell")
@interface GalleryItemCell : UITableViewCell
@property (nonatomic, weak) IBOutlet UIImageView * _Null_unspecified imgItem;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified lblName;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified lblCreatedDate;
- (void)awakeFromNib;
- (void)setSelected:(BOOL)selected animated:(BOOL)animated;
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * _Nullable)reuseIdentifier OBJC_DESIGNATED_INITIALIZER SWIFT_AVAILABILITY(ios,introduced=3.0);
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


IB_DESIGNABLE
SWIFT_CLASS("_TtC14VideoEditoriOS12GradientView")
@interface GradientView : UIView
@property (nonatomic, strong) IBInspectable UIColor * _Nonnull topColor;
@property (nonatomic, strong) IBInspectable UIColor * _Nonnull bottomColor;
@property (nonatomic, strong) IBInspectable UIColor * _Nonnull shadowColor;
@property (nonatomic) IBInspectable CGFloat shadowX;
@property (nonatomic) IBInspectable CGFloat shadowY;
@property (nonatomic) IBInspectable CGFloat shadowBlur;
@property (nonatomic) IBInspectable CGFloat startPointX;
@property (nonatomic) IBInspectable CGFloat startPointY;
@property (nonatomic) IBInspectable CGFloat endPointX;
@property (nonatomic) IBInspectable CGFloat endPointY;
@property (nonatomic) IBInspectable CGFloat cornerRadius;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) Class _Nonnull layerClass;)
+ (Class _Nonnull)layerClass SWIFT_WARN_UNUSED_RESULT;
- (void)layoutSubviews;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14VideoEditoriOS8HomeCell")
@interface HomeCell : UICollectionViewCell
@property (nonatomic, weak) IBOutlet CardView * _Null_unspecified viewForCellBg;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified lblForVideoEditName;
@property (nonatomic, weak) IBOutlet UIImageView * _Null_unspecified imgForUtilityIcon;
- (void)awakeFromNib;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

@class UICollectionView;
@class UIButton;
@class NSBundle;

SWIFT_CLASS("_TtC14VideoEditoriOS18HomeViewController")
@interface HomeViewController : UIViewController
@property (nonatomic, weak) IBOutlet UICollectionView * _Null_unspecified collectionView;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified videoPreviewView;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified videoPreviewBaseView;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified switchCameraBtn;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified headerLabel;
- (void)viewDidLoad;
- (IBAction)privacyPolicyBtn:(id _Nonnull)sender;
- (void)viewWillAppear:(BOOL)animated;
- (void)onPressCancelVideoCapture;
- (IBAction)onPressSwitchCamera:(UIButton * _Nonnull)sender;
- (IBAction)startCapture:(UIButton * _Nonnull)sender;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

@class AVCaptureFileOutput;
@class AVCaptureConnection;

@interface HomeViewController (SWIFT_EXTENSION(VideoEditoriOS)) <AVCaptureFileOutputRecordingDelegate>
- (void)captureOutput:(AVCaptureFileOutput * _Nonnull)output didFinishRecordingToOutputFileAtURL:(NSURL * _Nonnull)outputFileURL fromConnections:(NSArray<AVCaptureConnection *> * _Nonnull)connections error:(NSError * _Nullable)error;
@end

@class AssetsPickerViewController;
@class PHAsset;

@interface HomeViewController (SWIFT_EXTENSION(VideoEditoriOS)) <AssetsPickerViewControllerDelegate>
- (void)assetsPickerWithController:(AssetsPickerViewController * _Nonnull)controller selected:(NSArray<PHAsset *> * _Nonnull)assets;
- (BOOL)assetsPickerWithController:(AssetsPickerViewController * _Nonnull)controller shouldSelect:(PHAsset * _Nonnull)asset at:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
@end


@class UICollectionViewLayout;

@interface HomeViewController (SWIFT_EXTENSION(VideoEditoriOS)) <UICollectionViewDataSource, UICollectionViewDelegateFlowLayout>
- (NSInteger)collectionView:(UICollectionView * _Nonnull)collectionView numberOfItemsInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UICollectionViewCell * _Nonnull)collectionView:(UICollectionView * _Nonnull)collectionView cellForItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (void)collectionView:(UICollectionView * _Nonnull)collectionView didSelectItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (CGSize)collectionView:(UICollectionView * _Nonnull)collectionView layout:(UICollectionViewLayout * _Nonnull)collectionViewLayout sizeForItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (UIEdgeInsets)collectionView:(UICollectionView * _Nonnull)collectionView layout:(UICollectionViewLayout * _Nonnull)collectionViewLayout insetForSectionAtIndex:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (CGFloat)collectionView:(UICollectionView * _Nonnull)collectionView layout:(UICollectionViewLayout * _Nonnull)collectionViewLayout minimumInteritemSpacingForSectionAtIndex:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (CGFloat)collectionView:(UICollectionView * _Nonnull)collectionView layout:(UICollectionViewLayout * _Nonnull)collectionViewLayout minimumLineSpacingForSectionAtIndex:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS("_TtC14VideoEditoriOS22MergeVideoAddVideoCell")
@interface MergeVideoAddVideoCell : UICollectionViewCell
- (IBAction)onPressAddVideo:(UIButton * _Nonnull)sender;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14VideoEditoriOS14MergeVideoCell")
@interface MergeVideoCell : UICollectionViewCell
@property (nonatomic, weak) IBOutlet UIImageView * _Null_unspecified imageView;
- (void)awakeFromNib;
- (IBAction)onPressRemoveVideo:(UIButton * _Nonnull)sender;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

@class UISegmentedControl;
@class NSString;
@class NSError;
@class UILongPressGestureRecognizer;

SWIFT_CLASS("_TtC14VideoEditoriOS24MergeVideoViewController")
@interface MergeVideoViewController : UIViewController
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified playerView;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified convertBtn;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified playBtn;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified pauseBtn;
@property (nonatomic, weak) IBOutlet UICollectionView * _Null_unspecified collectionView;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified viewSelectedVideos;
@property (nonatomic, weak) IBOutlet UISegmentedControl * _Null_unspecified segmentVideoQuality;
- (void)viewDidLoad;
- (void)viewWillAppear:(BOOL)animated;
- (IBAction)closeAction:(id _Nonnull)sender;
- (void)itemDidFinishPlaying:(NSNotification * _Nonnull)notification;
- (void)videoWithVideoPath:(NSString * _Nonnull)videoPath didFinishSavingWithError:(NSError * _Nullable)error contextInfo:(id _Nonnull)info;
- (IBAction)onPressConvertVideo:(UIButton * _Nonnull)sender;
- (IBAction)onPressPlayVideo:(UIButton * _Nullable)sender;
- (IBAction)onPressPauseVideo:(UIButton * _Nullable)sender;
- (IBAction)onPressSegmentValueChanged:(UISegmentedControl * _Nonnull)sender;
- (void)handleLongGestureWithLongPress:(UILongPressGestureRecognizer * _Nonnull)longPress;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


@interface MergeVideoViewController (SWIFT_EXTENSION(VideoEditoriOS)) <AssetsPickerViewControllerDelegate>
- (void)assetsPickerWithController:(AssetsPickerViewController * _Nonnull)controller selected:(NSArray<PHAsset *> * _Nonnull)assets;
- (BOOL)assetsPickerWithController:(AssetsPickerViewController * _Nonnull)controller shouldSelect:(PHAsset * _Nonnull)asset at:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
@end



@interface MergeVideoViewController (SWIFT_EXTENSION(VideoEditoriOS)) <UICollectionViewDataSource, UICollectionViewDelegate>
- (NSInteger)collectionView:(UICollectionView * _Nonnull)collectionView numberOfItemsInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UICollectionViewCell * _Nonnull)collectionView:(UICollectionView * _Nonnull)collectionView cellForItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (void)collectionView:(UICollectionView * _Nonnull)collectionView didSelectItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (BOOL)collectionView:(UICollectionView * _Nonnull)collectionView canMoveItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (void)collectionView:(UICollectionView * _Nonnull)collectionView moveItemAtIndexPath:(NSIndexPath * _Nonnull)sourceIndexPath toIndexPath:(NSIndexPath * _Nonnull)destinationIndexPath;
@end


SWIFT_CLASS("_TtC14VideoEditoriOS26ReverseVideoViewController")
@interface ReverseVideoViewController : UIViewController
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified playerView;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified convertBtn;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified playBtn;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified pauseBtn;
- (void)viewDidLoad;
- (void)viewWillAppear:(BOOL)animated;
- (IBAction)closeAction:(id _Nonnull)sender;
- (void)itemDidFinishPlaying:(NSNotification * _Nonnull)notification;
- (void)videoWithVideoPath:(NSString * _Nonnull)videoPath didFinishSavingWithError:(NSError * _Nullable)error contextInfo:(id _Nonnull)info;
- (IBAction)onPressConvertVideo:(UIButton * _Nonnull)sender;
- (IBAction)onPressPlayVideo:(UIButton * _Nullable)sender;
- (IBAction)onPressPauseVideo:(UIButton * _Nullable)sender;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14VideoEditoriOS22SaveItemCollectionCell")
@interface SaveItemCollectionCell : UICollectionViewCell
@property (nonatomic, weak) IBOutlet UIImageView * _Null_unspecified imgForSaveItemPicture;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified btnForShareSaveItem;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified btnForAudioStartStop;
- (void)awakeFromNib;
- (IBAction)btnForPlayAudio:(UIButton * _Nonnull)sender;
- (IBAction)btnShareForData:(UIButton * _Nonnull)sender;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14VideoEditoriOS23SaveItemCollectionModel")
@interface SaveItemCollectionModel : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class UITableView;
@class NSLayoutConstraint;

SWIFT_CLASS("_TtC14VideoEditoriOS32SaveItemCollectionViewController")
@interface SaveItemCollectionViewController : UIViewController
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified previewImgView;
@property (nonatomic, weak) IBOutlet UIImageView * _Null_unspecified previewSaveItemImageView;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified playerView;
@property (nonatomic, weak) IBOutlet UITableView * _Null_unspecified tableView;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified noDataPromptLabel;
@property (nonatomic, strong) IBOutlet UIButton * _Null_unspecified editBtn;
@property (nonatomic, strong) IBOutlet UIButton * _Null_unspecified deleteBtn;
@property (nonatomic, strong) IBOutlet NSLayoutConstraint * _Null_unspecified heightOfViewEditingBtns;
- (void)viewDidLoad;
- (void)viewWillAppear:(BOOL)animated;
- (IBAction)closeBtn:(id _Nonnull)sender;
- (IBAction)btnCancelPreview:(UIButton * _Nonnull)sender;
- (IBAction)btnForSharePreview:(UIButton * _Nonnull)sender;
- (void)itemDidFinishPlaying:(NSNotification * _Nonnull)notification;
- (IBAction)onPressEdit:(UIButton * _Nullable)sender;
- (IBAction)onPressDeleteAll:(UIButton * _Nonnull)sender;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

@class AVAudioPlayer;

@interface SaveItemCollectionViewController (SWIFT_EXTENSION(VideoEditoriOS)) <AVAudioPlayerDelegate>
- (void)audioPlayerDidFinishPlaying:(AVAudioPlayer * _Nonnull)player successfully:(BOOL)flag;
@end


@class UITableViewRowAction;

@interface SaveItemCollectionViewController (SWIFT_EXTENSION(VideoEditoriOS)) <UITableViewDataSource, UITableViewDelegate>
- (NSInteger)tableView:(UITableView * _Nonnull)tableView numberOfRowsInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UITableViewCell * _Nonnull)tableView:(UITableView * _Nonnull)tableView cellForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (void)tableView:(UITableView * _Nonnull)tableView didSelectRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (NSArray<UITableViewRowAction *> * _Nullable)tableView:(UITableView * _Nonnull)tableView editActionsForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (CGFloat)tableView:(UITableView * _Nonnull)tableView heightForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS("_TtC14VideoEditoriOS19SaveItemGalleryCell")
@interface SaveItemGalleryCell : UICollectionViewCell
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified lblForSaveFunctionalityName;
@property (nonatomic, weak) IBOutlet UIImageView * _Null_unspecified imgForUtilityIcon;
- (void)awakeFromNib;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14VideoEditoriOS29SaveItemGalleryViewController")
@interface SaveItemGalleryViewController : UIViewController
- (void)viewDidLoad;
- (IBAction)closeAction:(id _Nonnull)sender;
- (void)viewWillAppear:(BOOL)animated;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


@interface SaveItemGalleryViewController (SWIFT_EXTENSION(VideoEditoriOS)) <UICollectionViewDataSource, UICollectionViewDelegateFlowLayout>
- (NSInteger)collectionView:(UICollectionView * _Nonnull)collectionView numberOfItemsInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UICollectionViewCell * _Nonnull)collectionView:(UICollectionView * _Nonnull)collectionView cellForItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (void)collectionView:(UICollectionView * _Nonnull)collectionView didSelectItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (CGSize)collectionView:(UICollectionView * _Nonnull)collectionView layout:(UICollectionViewLayout * _Nonnull)collectionViewLayout sizeForItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (UIEdgeInsets)collectionView:(UICollectionView * _Nonnull)collectionView layout:(UICollectionViewLayout * _Nonnull)collectionViewLayout insetForSectionAtIndex:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (CGFloat)collectionView:(UICollectionView * _Nonnull)collectionView layout:(UICollectionViewLayout * _Nonnull)collectionViewLayout minimumInteritemSpacingForSectionAtIndex:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (CGFloat)collectionView:(UICollectionView * _Nonnull)collectionView layout:(UICollectionViewLayout * _Nonnull)collectionViewLayout minimumLineSpacingForSectionAtIndex:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
@end

@class UIStepper;

SWIFT_CLASS("_TtC14VideoEditoriOS27SlowFastVideoViewController")
@interface SlowFastVideoViewController : UIViewController
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified playerView;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified convertBtn;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified playBtn;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified pauseBtn;
@property (nonatomic, strong) IBOutlet UILabel * _Null_unspecified scaleSpeedLabel;
@property (nonatomic, strong) IBOutlet UIStepper * _Null_unspecified stepper;
@property (nonatomic, strong) IBOutlet UIView * _Null_unspecified videoSpeedControlsView;
- (void)viewDidLoad;
- (void)viewWillAppear:(BOOL)animated;
- (IBAction)closeAction:(id _Nonnull)sender;
- (void)itemDidFinishPlaying:(NSNotification * _Nonnull)notification;
- (void)videoWithVideoPath:(NSString * _Nonnull)videoPath didFinishSavingWithError:(NSError * _Nullable)error contextInfo:(id _Nonnull)info;
- (IBAction)onPressConvertVideo:(UIButton * _Nonnull)sender;
- (IBAction)onPressPlayVideo:(UIButton * _Nullable)sender;
- (IBAction)onPressPauseVideo:(UIButton * _Nullable)sender;
- (IBAction)onPressSegment:(UISegmentedControl * _Nonnull)sender;
- (IBAction)onPressStepper:(UIStepper * _Nonnull)sender;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

@class TrimmerView;
@class FLAnimatedImageView;

SWIFT_CLASS("_TtC14VideoEditoriOS21TrimmerViewController")
@interface TrimmerViewController : UIViewController
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified playerView;
@property (nonatomic, weak) IBOutlet TrimmerView * _Null_unspecified trimmerView;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified convertBtn;
@property (nonatomic, strong) IBOutlet FLAnimatedImageView * _Null_unspecified loadPreviewImageView;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified playBtn;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified pauseBtn;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified gifBtn;
- (void)viewDidLoad;
- (IBAction)closeAction:(id _Nonnull)sender;
- (void)viewWillAppear:(BOOL)animated;
- (void)viewDidDisappear:(BOOL)animated;
- (IBAction)onPressConvertVideo:(UIButton * _Nonnull)sender;
- (IBAction)onPressPlayVideo:(UIButton * _Nullable)sender;
- (IBAction)onPressPauseVideo:(UIButton * _Nullable)sender;
- (IBAction)onPressGIF:(UIButton * _Nullable)sender;
- (void)itemDidFinishPlaying:(NSNotification * _Nonnull)notification;
- (void)onPlaybackTimeChecker;
- (void)didFinishAnimatingImageView;
- (void)videoWithVideoPath:(NSString * _Nonnull)videoPath didFinishSavingWithError:(NSError * _Nullable)error contextInfo:(id _Nonnull)info;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


@interface TrimmerViewController (SWIFT_EXTENSION(VideoEditoriOS)) <AVAudioPlayerDelegate>
- (void)audioPlayerDidFinishPlaying:(AVAudioPlayer * _Nonnull)player successfully:(BOOL)flag;
@end

@class UIGestureRecognizer;

@interface TrimmerViewController (SWIFT_EXTENSION(VideoEditoriOS)) <UIGestureRecognizerDelegate>
- (BOOL)gestureRecognizer:(UIGestureRecognizer * _Nonnull)gestureRecognizer shouldBeRequiredToFailByGestureRecognizer:(UIGestureRecognizer * _Nonnull)otherGestureRecognizer SWIFT_WARN_UNUSED_RESULT;
@end






SWIFT_CLASS("_TtC14VideoEditoriOS15VUVideoFilterVC")
@interface VUVideoFilterVC : UIViewController
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified playerView;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified convertBtn;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified playBtn;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified pauseBtn;
@property (nonatomic, weak) IBOutlet UICollectionView * _Null_unspecified collectionView;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified filtersView;
- (void)viewDidLoad;
- (void)viewWillAppear:(BOOL)animated;
- (IBAction)closebtnAction:(id _Nonnull)sender;
- (void)itemDidFinishPlaying:(NSNotification * _Nonnull)notification;
- (void)videoWithVideoPath:(NSString * _Nonnull)videoPath didFinishSavingWithError:(NSError * _Nullable)error contextInfo:(id _Nonnull)info;
- (IBAction)onPressConvertVideo:(UIButton * _Nonnull)sender;
- (IBAction)onPressPlayVideo:(UIButton * _Nullable)sender;
- (IBAction)onPressPauseVideo:(UIButton * _Nullable)sender;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


@interface VUVideoFilterVC (SWIFT_EXTENSION(VideoEditoriOS)) <UICollectionViewDataSource, UICollectionViewDelegate>
- (NSInteger)collectionView:(UICollectionView * _Nonnull)collectionView numberOfItemsInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UICollectionViewCell * _Nonnull)collectionView:(UICollectionView * _Nonnull)collectionView cellForItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (void)collectionView:(UICollectionView * _Nonnull)collectionView didSelectItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
@end


SWIFT_CLASS("_TtC14VideoEditoriOS15VideoFilterCell")
@interface VideoFilterCell : UICollectionViewCell
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified filterNameLabel;
@property (nonatomic, weak) IBOutlet UIImageView * _Null_unspecified imageView;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified initialLabel;
- (void)awakeFromNib;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14VideoEditoriOS16VideoFilterModel")
@interface VideoFilterModel : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC14VideoEditoriOS12VideoUtility")
@interface VideoUtility : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14VideoEditoriOS28WatermarkVideoViewController")
@interface WatermarkVideoViewController : UIViewController
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified playerView;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified convertBtn;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified playBtn;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified pauseBtn;
@property (nonatomic, strong) IBOutlet UIButton * _Null_unspecified chooseImageBtn;
@property (nonatomic, strong) IBOutlet UIButton * _Null_unspecified selectPositionBtn;
@property (nonatomic, strong) IBOutlet UIImageView * _Null_unspecified watermarkImageView;
@property (nonatomic, strong) IBOutlet UILabel * _Null_unspecified selectedPositionLabel;
@property (nonatomic, strong) IBOutlet UIButton * _Null_unspecified topLeftBtn;
@property (nonatomic, strong) IBOutlet UIButton * _Null_unspecified topRightBtn;
@property (nonatomic, strong) IBOutlet UIButton * _Null_unspecified bottomLeftBtn;
@property (nonatomic, strong) IBOutlet UIButton * _Null_unspecified bottomRightBtn;
@property (nonatomic, strong) IBOutlet UIView * _Null_unspecified selectPositionMainView;
@property (nonatomic, strong) IBOutlet GradientView * _Null_unspecified selectPositionSubView;
@property (nonatomic, strong) IBOutlet UILabel * _Null_unspecified noImageSelectedLabel;
@property (nonatomic, strong) IBOutlet UIView * _Null_unspecified watermarkControlsView;
- (void)viewDidLoad;
- (IBAction)closeAction:(id _Nonnull)sender;
- (void)viewWillAppear:(BOOL)animated;
- (void)itemDidFinishPlaying:(NSNotification * _Nonnull)notification;
- (void)videoWithVideoPath:(NSString * _Nonnull)videoPath didFinishSavingWithError:(NSError * _Nullable)error contextInfo:(id _Nonnull)info;
- (IBAction)onPressConvertVideo:(UIButton * _Nonnull)sender;
- (IBAction)onPressPlayVideo:(UIButton * _Nullable)sender;
- (IBAction)onPressPauseVideo:(UIButton * _Nullable)sender;
- (IBAction)onPressChooseImage:(UIButton * _Nonnull)sender;
- (IBAction)onPressSelectPosition:(UIButton * _Nonnull)sender;
- (IBAction)onPressCloseViewPosition:(UIButton * _Nonnull)sender;
- (IBAction)onPressTopLeft:(UIButton * _Nonnull)sender;
- (IBAction)onPressTopRight:(UIButton * _Nonnull)sender;
- (IBAction)onPressBottomLeft:(UIButton * _Nonnull)sender;
- (IBAction)onPressBottomRight:(UIButton * _Nonnull)sender;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


@class UITouch;
@class UIEvent;

IB_DESIGNABLE
SWIFT_CLASS("_TtC14VideoEditoriOS7XButton")
@interface XButton : UIButton
@property (nonatomic) IBInspectable BOOL animate;
@property (nonatomic) IBInspectable double animateDelay;
@property (nonatomic) IBInspectable NSInteger animateFrom;
@property (nonatomic) IBInspectable BOOL popIn;
@property (nonatomic) IBInspectable double popInDelay;
- (void)drawRect:(CGRect)rect;
- (BOOL)beginTrackingWithTouch:(UITouch * _Nonnull)touch withEvent:(UIEvent * _Nullable)event SWIFT_WARN_UNUSED_RESULT;
- (void)endTrackingWithTouch:(UITouch * _Nullable)touch withEvent:(UIEvent * _Nullable)event;
@property (nonatomic) IBInspectable CGFloat cornerRadius;
@property (nonatomic) IBInspectable CGFloat borderWidth;
@property (nonatomic, strong) IBInspectable UIColor * _Nonnull borderColor;
@property (nonatomic) IBInspectable CGFloat shadowOpacity;
@property (nonatomic, strong) IBInspectable UIColor * _Nonnull shadowColor;
@property (nonatomic) IBInspectable CGFloat shadowRadius;
@property (nonatomic) IBInspectable CGSize shadowOffset;
@property (nonatomic, strong) IBInspectable UIColor * _Nonnull firstColor;
@property (nonatomic, strong) IBInspectable UIColor * _Nonnull secondColor;
@property (nonatomic) IBInspectable BOOL horizontalGradient;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) Class _Nonnull layerClass;)
+ (Class _Nonnull)layerClass SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

@class UIImage;

IB_DESIGNABLE
SWIFT_CLASS("_TtC14VideoEditoriOS10XImageView")
@interface XImageView : UIImageView
@property (nonatomic, strong) IBInspectable UIColor * _Nonnull borderColor;
@property (nonatomic) IBInspectable CGFloat borderWidth;
@property (nonatomic) IBInspectable CGFloat cornerRadius;
@property (nonatomic) IBInspectable double pulseDelay;
@property (nonatomic) IBInspectable BOOL popIn;
@property (nonatomic) IBInspectable double popInDelay;
@property (nonatomic) IBInspectable CGFloat shadowOpacity;
@property (nonatomic, strong) IBInspectable UIColor * _Nonnull shadowColor;
@property (nonatomic) IBInspectable CGFloat shadowRadius;
@property (nonatomic) IBInspectable CGFloat shadowOffsetY;
- (void)layoutSubviews;
- (void)drawRect:(CGRect)rect;
- (void)awakeFromNib;
- (nonnull instancetype)initWithImage:(UIImage * _Nullable)image OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithImage:(UIImage * _Nullable)image highlightedImage:(UIImage * _Nullable)highlightedImage OBJC_DESIGNATED_INITIALIZER SWIFT_AVAILABILITY(ios,introduced=3.0);
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


IB_DESIGNABLE
SWIFT_CLASS("_TtC14VideoEditoriOS6XLabel")
@interface XLabel : UILabel
@property (nonatomic) IBInspectable CGFloat cornerRadius;
@property (nonatomic) IBInspectable CGFloat borderWidth;
@property (nonatomic, strong) IBInspectable UIColor * _Nonnull borderColor;
@property (nonatomic) IBInspectable CGFloat rotationAngle;
@property (nonatomic) IBInspectable CGFloat shadowOpacity;
@property (nonatomic, strong) IBInspectable UIColor * _Nonnull shadowColorLayer;
@property (nonatomic) IBInspectable CGFloat shadowRadius;
@property (nonatomic) IBInspectable CGSize shadowOffsetLayer;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


IB_DESIGNABLE
SWIFT_CLASS("_TtC14VideoEditoriOS19XRadialGradientView")
@interface XRadialGradientView : UIView
@property (nonatomic, strong) IBInspectable UIColor * _Nonnull InsideColor;
@property (nonatomic, strong) IBInspectable UIColor * _Nonnull OutsideColor;
- (void)drawRect:(CGRect)rect;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


IB_DESIGNABLE
SWIFT_CLASS("_TtC14VideoEditoriOS7XSlider")
@interface XSlider : UISlider
@property (nonatomic, strong) IBInspectable UIImage * _Nullable thumbImage;
@property (nonatomic, strong) IBInspectable UIImage * _Nullable thumbHighlightedImage;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


IB_DESIGNABLE
SWIFT_CLASS("_TtC14VideoEditoriOS10XTextField")
@interface XTextField : UITextField
@property (nonatomic, strong) IBInspectable UIImage * _Nullable leftImage;
@property (nonatomic) IBInspectable CGFloat leftPadding;
@property (nonatomic, strong) IBInspectable UIImage * _Nullable rightImage;
@property (nonatomic) IBInspectable CGFloat rightPadding;
@property (nonatomic) IBInspectable CGFloat cornerRadius;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


IB_DESIGNABLE
SWIFT_CLASS("_TtC14VideoEditoriOS5XView")
@interface XView : UIView
@property (nonatomic, strong) IBInspectable UIColor * _Nonnull firstColor;
@property (nonatomic, strong) IBInspectable UIColor * _Nonnull secondColor;
@property (nonatomic) IBInspectable BOOL horizontalGradient;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) Class _Nonnull layerClass;)
+ (Class _Nonnull)layerClass SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, strong) IBInspectable UIColor * _Nonnull borderColor;
@property (nonatomic) IBInspectable CGFloat borderWidth;
@property (nonatomic) IBInspectable CGFloat cornerRadius;
@property (nonatomic) IBInspectable CGFloat shadowOpacity;
@property (nonatomic, strong) IBInspectable UIColor * _Nonnull shadowColor;
@property (nonatomic) IBInspectable CGFloat shadowRadius;
@property (nonatomic) IBInspectable CGFloat shadowOffsetY;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


IB_DESIGNABLE
SWIFT_CLASS("_TtC14VideoEditoriOS15XViewController")
@interface XViewController : UIViewController
@property (nonatomic) IBInspectable BOOL lightStatusBar;
@property (nonatomic, readonly) UIStatusBarStyle preferredStatusBarStyle;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

@class UIVisualEffect;

SWIFT_CLASS("_TtC14VideoEditoriOS17XVisualEffectView")
@interface XVisualEffectView : UIVisualEffectView
@property (nonatomic, strong) IBInspectable UIColor * _Nonnull borderColor;
@property (nonatomic) IBInspectable CGFloat borderWidth;
@property (nonatomic) IBInspectable CGFloat cornerRadius;
- (nonnull instancetype)initWithEffect:(UIVisualEffect * _Nullable)effect OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#pragma clang diagnostic pop
#endif
